import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from 'antd';
import React, { useCallback, useEffect, useRef, useState } from 'react';

const Render = ({ data }: any) => {
    const [page, setPage] = useState<any>();
    const handleAmis = useCallback(async () => {
        if (window?.document) {
            const { render } = await import("amis");
            const renderPage = render(data)
            return <>{renderPage}</>
        }

    }, [data]);

    useEffect(() => {
        handleAmis().then((page) => {
            setPage(page)
        })
    }, [handleAmis])
    console.log('page', page);


    return (
        <div className={styles.container}>
            <Head>
                <title>Hello world</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Button type='primary'>按钮</Button>
                <div id='amis' >{page}</div>

            </main>


        </div>
    )
}
export default Render;